In [1]:
#iImporting the Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [2]:
df= pd.read_csv(r"C:\Users\ayush\Desktop\Machine Learning Projects\House Data\kc_house_data.csv")

# Exploratory Data Analysis
* Now we would Find some general properties of the Data.

In [3]:
df.head(20)

id             date      price  bedrooms  bathrooms  sqft_living  \
0   7129300520  20141013T000000   221900.0         3       1.00         1180   
1   6414100192  20141209T000000   538000.0         3       2.25         2570   
2   5631500400  20150225T000000   180000.0         2       1.00          770   
3   2487200875  20141209T000000   604000.0         4       3.00         1960   
4   1954400510  20150218T000000   510000.0         3       2.00         1680   
5   7237550310  20140512T000000  1225000.0         4       4.50         5420   
6   1321400060  20140627T000000   257500.0         3       2.25         1715   
7   2008000270  20150115T000000   291850.0         3       1.50         1060   
8   2414600126  20150415T000000   229500.0         3       1.00         1780   
9   3793500160  20150312T000000   323000.0         3       2.50         1890   
10  1736800520  20150403T000000   662500.0         3       2.50         3560   
11  9212900260  20140527T000000   468000.0         2       1.00         1160   
12   114101516  20140528T000000   310000.0         3       1.00         1430   
13  6054650070  20141007T000000   400000.0         3       1.75         1370   
14  1175000570  20150312T000000   530000.0         5       2.00         1810   
15  9297300055  20150124T000000   650000.0         4       3.00         2950   
16  1875500060  20140731T000000   395000.0         3       2.00         1890   
17  6865200140  20140529T000000   485000.0         4       1.00         1600   
18    16000397  20141205T000000   189000.0         2       1.00         1200   
19  7983200060  20150424T000000   230000.0         3       1.00         1250   

    sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0       5650     1.0           0     0  ...      7        1180              0   
1       7242     2.0           0     0  ...      7        2170            400   
2      10000     1.0           0     0  ...      6         770              0   
3       5000     1.0           0     0  ...      7        1050            910   
4       8080     1.0           0     0  ...      8        1680              0   
5     101930     1.0           0     0  ...     11        3890           1530   
6       6819     2.0           0     0  ...      7        1715              0   
7       9711     1.0           0     0  ...      7        1060              0   
8       7470     1.0           0     0  ...      7        1050            730   
9       6560     2.0           0     0  ...      7        1890              0   
10      9796     1.0           0     0  ...      8        1860           1700   
11      6000     1.0           0     0  ...      7         860            300   
12     19901     1.5           0     0  ...      7        1430              0   
13      9680     1.0           0     0  ...      7        1370              0   
14      4850     1.5           0     0  ...      7        1810              0   
15      5000     2.0           0     3  ...      9        1980            970   
16     14040     2.0           0     0  ...      7        1890              0   
17      4300     1.5           0     0  ...      7        1600              0   
18      9850     1.0           0     0  ...      7        1200              0   
19      9774     1.0           0     0  ...      7        1250              0   

    yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0       1955             0    98178  47.5112 -122.257           1340   
1       1951          1991    98125  47.7210 -122.319           1690   
2       1933             0    98028  47.7379 -122.233           2720   
3       1965             0    98136  47.5208 -122.393           1360   
4       1987             0    98074  47.6168 -122.045           1800   
5       2001             0    98053  47.6561 -122.005           4760   
6       1995             0    98003  47.3097 -122.327           2238   
7       1963             0    98198  47.4095 -122.315

In [4]:
df.tail(20)

id             date      price  bedrooms  bathrooms  \
21593  8672200110  20150317T000000  1088000.0         5       3.75   
21594  5087900040  20141017T000000   350000.0         4       2.75   
21595  1972201967  20141031T000000   520000.0         2       2.25   
21596  7502800100  20140813T000000   679950.0         5       2.75   
21597   191100405  20150421T000000  1575000.0         4       3.25   
21598  8956200760  20141013T000000   541800.0         4       2.50   
21599  7202300110  20140915T000000   810000.0         4       3.00   
21600   249000205  20141015T000000  1537000.0         5       3.75   
21601  5100403806  20150407T000000   467000.0         3       2.50   
21602   844000965  20140626T000000   224000.0         3       1.75   
21603  7852140040  20140825T000000   507250.0         3       2.50   
21604  9834201367  20150126T000000   429000.0         3       2.00   
21605  3448900210  20141014T000000   610685.0         4       2.50   
21606  7936000429  20150326T000000  1007500.0         4       3.50   
21607  2997800021  20150219T000000   475000.0         3       2.50   
21608   263000018  20140521T000000   360000.0         3       2.50   
21609  6600060120  20150223T000000   400000.0         4       2.50   
21610  1523300141  20140623T000000   402101.0         2       0.75   
21611   291310100  20150116T000000   400000.0         3       2.50   
21612  1523300157  20141015T000000   325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
21593         4170      8142     2.0           0     2  ...     10   
21594         2500      5995     2.0           0     0  ...      8   
21595         1530       981     3.0           0     0  ...      8   
21596         3600      9437     2.0           0     0  ...      9   
21597         3410     10125     2.0           0     0  ...     10   
21598         3118      7866     2.0           0     2  ...      9   
21599         3990      7838     2.0           0     0  ...      9   
21600         4470      8088     2.0           0     0  ...     11   
21601         1425      1179     3.0           0     0  ...      8   
21602         1500     11968     1.0           0     0  ...      6   
21603         2270      5536     2.0           0     0  ...      8   
21604         1490      1126     3.0           0     0  ...      8   
21605         2520      6023     2.0           0     0  ...      9   
21606         3510      7200     2.0           0     0  ...      9   
21607         1310      1294     2.0           0     0  ...      8   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
21593        4170              0      2006             0    98056  47.5354   
21594        2500              0      2008             0    98042  47.3749   
21595        1480             50      2006             0    98103  47.6533   
21596        3600              0      2014             0    98059  47.4822   
21597        3410              0      2007             0    98040  47.5653   
21598        3118              0      2014             0    98001  47.2931   
21599        3990              0      2003             0    98053  47.6857   
21600        4470              0      2008             0    98004  47.6321   
21601        1425              0      2008             0    98125  47.6963   
21602        1500              0      2014             0    98010  47.3095   
21603        2270              0      2003             0    98065  47.5389   
21604        1490              0      2014             0    98144  47.5699   
21605        2520              0      2014             0   

In [5]:
#The Data has no Missing Values
df.isna().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [6]:
df.describe()

id         price      bedrooms     bathrooms   sqft_living  \
count  2.161300e+04  2.161300e+04  21613.000000  21613.000000  21613.000000   
mean   4.580302e+09  5.400881e+05      3.370842      2.114757   2079.899736   
std    2.876566e+09  3.671272e+05      0.930062      0.770163    918.440897   
min    1.000102e+06  7.500000e+04      0.000000      0.000000    290.000000   
25%    2.123049e+09  3.219500e+05      3.000000      1.750000   1427.000000   
50%    3.904930e+09  4.500000e+05      3.000000      2.250000   1910.000000   
75%    7.308900e+09  6.450000e+05      4.000000      2.500000   2550.000000   
max    9.900000e+09  7.700000e+06     33.000000      8.000000  13540.000000   

           sqft_lot        floors    waterfront          view     condition  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  21613.000000   
mean   1.510697e+04      1.494309      0.007542      0.234303      3.409430   
std    4.142051e+04      0.539989      0.086517      0.766318      0.650743   
min    5.200000e+02      1.000000      0.000000      0.000000      1.000000   
25%    5.040000e+03      1.000000      0.000000      0.000000      3.000000   
50%    7.618000e+03      1.500000      0.000000      0.000000      3.000000   
75%    1.068800e+04      2.000000      0.000000      0.000000      4.000000   
max    1.651359e+06      3.500000      1.000000      4.000000      5.000000   

              grade    sqft_above  sqft_basement      yr_built  yr_renovated  \
count  21613.000000  21613.000000   21613.000000  21613.000000  21613.000000   
mean       7.656873   1788.390691     291.509045   1971.005136     84.402258   
std        1.175459    828.090978     442.575043     29.373411    401.679240   
min        1.000000    290.000000       0.000000   1900.000000      0.000000   
25%        7.000000   1190.000000       0.000000   1951.000000      0.000000   
50%        7.000000   1560.000000       0.000000   1975.000000      0.000000   
75%        8.000000   2210.000000     560.000000   1997.000000      0.000000   
max       13.000000   9410.000000    4820.000000   2015.000000   2015.000000   

            zipcode           lat          long  sqft_living15     sqft_lot15  
count  21613.000000  21613.000000  21613.000000   21613.000000   21613.000000  
mean   98077.939805     47.560053   -122.213896    1986.552492   12768.455652  
std       53.505026      0.138564      0.140828     685.391304   27304.179631  
min    98001.000000     47.155900   -122.519000     399.000000     651.000000  
25%    98033.000000     47.471000   -122.328000    1490.000000    5100.000000  
50%    98065.000000     47.571800   -122.230000    1840.000000    7620.000000  
75%    98118.000000     47.678000   -122.125000    2360.000000   10083.000000  
max    98199.000000     47.777600   -121.315000    6210.000000  871200.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

* Out of the columns present in the data, we see that id, date, yr_built, yr_rennovated, zipcode, lat, long would not be contributing to the price of the house.

In [8]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

* Spliitting data into useful columns

In [9]:
x=df[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement',
        'sqft_living15', 'sqft_lot15']]

In [10]:
x

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0             3       1.00         1180      5650     1.0           0     0   
1             3       2.25         2570      7242     2.0           0     0   
2             2       1.00          770     10000     1.0           0     0   
3             4       3.00         1960      5000     1.0           0     0   
4             3       2.00         1680      8080     1.0           0     0   
...         ...        ...          ...       ...     ...         ...   ...   
21608         3       2.50         1530      1131     3.0           0     0   
21609         4       2.50         2310      5813     2.0           0     0   
21610         2       0.75         1020      1350     2.0           0     0   
21611         3       2.50         1600      2388     2.0           0     0   
21612         2       0.75         1020      1076     2.0           0     0   

       condition  grade  sqft_above  sqft_basement  sqft_living15  sqft_lot15  
0              3      7        1180              0           1340        5650  
1              3      7        2170            400           1690        7639  
2              3      6         770              0           2720        8062  
3              5      7        1050            910           1360        5000  
4              3      8        1680              0           1800        7503  
...          ...    ...         ...            ...            ...         ...  
21608          3      8        1530              0           1530        1509  
21609          3      8        2310              0           1830        7200  
21610          3      7        1020              0           1020        2007  
21611          3      8        1600              0           1410        1287  
21612          3      7        1020              0           1020        1357  

[21613 rows x 13 columns]

In [11]:
y= df["price"]

In [12]:
y

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

# Machine Learning

* We would split the data into train and test.

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.25,random_state=42)

In [14]:
x_train

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
5945          4       2.25         1810      9240     2.0           0     0   
8423          3       2.50         1600      2788     2.0           0     0   
13488         4       2.50         1720      8638     2.0           0     0   
20731         2       2.25         1240       705     2.0           0     0   
2358          3       2.00         1280     13356     1.0           0     0   
...         ...        ...          ...       ...     ...         ...   ...   
11964         3       1.50         1000      6914     1.0           0     0   
21575         3       2.50         3087      5002     2.0           0     0   
5390          3       2.50         2120      4780     2.0           0     0   
860           1       0.75          380     15000     1.0           0     0   
15795         4       2.50         3130      5999     2.0           0     0   

       condition  grade  sqft_above  sqft_basement  sqft_living15  sqft_lot15  
5945           3      7        1810              0           1660        9240  
8423           4      7        1600              0           1720        3605  
13488          3      8        1720              0           1870        7455  
20731          3      7        1150             90           1240         750  
2358           3      7        1280              0           1590        8071  
...          ...    ...         ...            ...            ...         ...  
11964          3      7        1000              0           1000        6947  
21575          3      8        3087              0           2927        5183  
5390           3      7        2120              0           1690        2650  
860            3      5         380              0           1170       15000  
15795          3      7        3130              0           3020        5997  

[16209 rows x 13 columns]

In [15]:
x_test

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
735           4       2.25         2070      8893     2.0           0     0   
2830          5       3.00         2900      6730     1.0           0     0   
4106          4       2.50         3770     10893     2.0           0     2   
16218         3       3.50         4560     14608     2.0           0     2   
19964         3       2.50         2550      5376     2.0           0     0   
...         ...        ...          ...       ...     ...         ...   ...   
11144         4       2.50         2820     15000     2.0           0     0   
17803         3       2.00         1460      6250     1.5           0     0   
268           3       2.50         2070      9900     1.0           0     0   
518           4       2.25         4760      8036     2.5           0     0   
8482          4       1.75         1720      8300     1.0           0     0   

       condition  grade  sqft_above  sqft_basement  sqft_living15  sqft_lot15  
735            4      8        2070              0           2390        7700  
2830           5      8        1830           1070           2370        6283  
4106           3     11        3770              0           3710        9685  
16218          3     12        4560              0           4050       14226  
19964          3      9        2550              0           2250        4050  
...          ...    ...         ...            ...            ...         ...  
11144          4      9        2820              0           2440       15000  
17803          4      7        1460              0           1690        4750  
268            3      8        1420            650           2070        8250  
518            5      9        3390           1370           2950        9323  
8482           4      8        1720              0           1840        8300  

[5404 rows x 13 columns]

In [16]:
y_train

5945     268643.0
8423     245000.0
13488    200000.0
20731    352499.0
2358     232000.0
           ...   
11964    378000.0
21575    399950.0
5390     575000.0
860      245000.0
15795    315000.0
Name: price, Length: 16209, dtype: float64

In [17]:
y_test

735       365000.0
2830      865000.0
4106     1038000.0
16218    1490000.0
19964     711000.0
           ...    
11144     650000.0
17803     705000.0
268       272500.0
518      2250000.0
8482      330000.0
Name: price, Length: 5404, dtype: float64

* After splitting the data into training and test, would then use StandardScaler on the training data.

* Using standardscaler so as to arrange the data in form of standard normal distribution.

In [18]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train_std=sc.fit_transform(x_train)
x_test_std= sc.transform(x_test)

In [19]:
x_train_std

array([[ 0.67740215,  0.17896268, -0.2902756 , ..., -0.65784273,
        -0.47391081, -0.12979094],
       [-0.3941321 ,  0.50566682, -0.52181284, ..., -0.65784273,
        -0.38591932, -0.33901903],
       [ 0.67740215,  0.50566682, -0.38950585, ..., -0.65784273,
        -0.1659406 , -0.19606816],
       ...,
       [-0.3941321 ,  0.50566682,  0.05151748, ..., -0.65784273,
        -0.42991507, -0.37447827],
       [-2.53720059, -1.78126215, -1.86693398, ..., -0.65784273,
        -1.19250798,  0.0840784 ],
       [ 0.67740215,  0.50566682,  1.16510137, ..., -0.65784273,
         1.52056295, -0.25020384]])

In [20]:
x_test_std

array([[ 0.67740215,  0.17896268, -0.00361044, ..., -0.65784273,
         0.59665231, -0.18697129],
       [ 1.7489364 ,  1.15907509,  0.91151296, ...,  1.78181907,
         0.56732181, -0.23958463],
       [ 0.67740215,  0.50566682,  1.87073868, ..., -0.65784273,
         2.53246508, -0.11326805],
       ...,
       [-0.3941321 ,  0.50566682, -0.00361044, ...,  0.82419481,
         0.12736437, -0.16654974],
       [ 0.67740215,  0.17896268,  2.96227141, ...,  2.4658364 ,
         1.41790621, -0.12670915],
       [ 0.67740215, -0.4744456 , -0.38950585, ..., -0.65784273,
        -0.20993635, -0.16469323]])

* Now we would be following the machine learning pathway and would be implementing linear regression.
The pathcould be accessed at https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [21]:
from sklearn import linear_model
lr= linear_model.LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [22]:
y_pred= lr.predict(x_test)

In [23]:
y_pred

array([ 556356.22155339,  754935.30161098, 1248027.99858549, ...,
        557754.90483083, 1243486.0514146 ,  496918.69658139])

In [24]:
y_pred_reshape= np.reshape(y_pred, (len(y_pred),1))
y_pred_reshape

array([[ 556356.22155339],
       [ 754935.30161098],
       [1248027.99858549],
       ...,
       [ 557754.90483083],
       [1243486.0514146 ],
       [ 496918.69658139]])

* Now we would be printing accuracy scores using coefficient of determination, Mean Sqaured Error and mean absolute error.

In [25]:
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
r_square=r2_score(y_test,y_pred)

In [26]:
r_square

0.6196186509196234

In [27]:
mae= mean_absolute_error(y_test,y_pred)
mae

153674.21944538876

In [28]:
mse=mean_squared_error(y_test,y_pred)
mse

56900342344.13416

In [29]:
accuracy= {"Method":["Coefficient of Determination","Mean Sqaured Error" ,"Mean Absolute Error"],"Score":[float(r_square), float(mse),float(mae)] }
pd.DataFrame.from_dict(accuracy)

Method         Score
0  Coefficient of Determination  6.196187e-01
1            Mean Sqaured Error  5.690034e+10
2           Mean Absolute Error  1.536742e+05

* Predicting the Price 

In [30]:
data= [[3,1,1520,5000,1,0,0,3,8,1000,1,2000,5000]]

data=sc.transform(data)
data


array([[-0.3941321 , -1.45455802, -0.61001751, -0.25416096, -0.91862561,
        -0.08378769, -0.30696369, -0.62600049,  0.29634963, -0.95492662,
        -0.65556267,  0.02470763, -0.28722254]])

In [31]:
data_predict=lr.predict(data)

In [32]:
print("The Predicted price of the House is ", int(data_predict) )

The Predicted price of the House is  -699373
